version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
      - TZ=${TZ}
    ports:
    - ${APP_PORT}:8000
    volumes:
    - ${PROJECT_PATH}:/work
    - ./docker/ash:/etc/profile.d
    - ./logs:/var/log/php
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
#    - DB_CONNECTION=mysql
#    - DB_HOST=db
#    - DB_DATABASE=${DB_NAME}
#    - DB_USERNAME=${DB_USER}
#    - DB_PASSWORD=${DB_PASS}
    - TZ=${TZ}
    - MAIL_HOST=${MAIL_HOST}
    - MAIL_PORT=${MAIL_PORT}
#    - CACHE_DRIVER=redis
#    - SESSION_DRIVER=redis
#    - QUEUE_DRIVER=redis
#    - REDIS_HOST=redis

  web:
    image: nginx:1.17-alpine

    # depends_on : 依存関係
    depends_on:
    - app
    ports:
    - ${WEB_PORT}:80
    volumes:
    - ${PROJECT_PATH}:/work
    - ./logs:/var/log/nginx
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
    - TZ=${TZ}

  db:
#    image: mysql:5.7
    image: mariadb:10.4
#    restart: always
    volumes:
    - db-store:/var/lib/mysql
#    - ./logs:/var/log/mysql # ここを有効にするとエラー
#    - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
    - MYSQL_DATABASE=${DB_NAME}
    - MYSQL_USER=${DB_USER}
    - MYSQL_PASSWORD=${DB_PASS}
    - MYSQL_ROOT_PASSWORD=${DB_PASS}
    - TZ=${TZ}
    ports:
    - ${DB_PORT}:3306


volumes:
  db-store:



